### ISSUE TITLE
[BUG] json endpoint absent

### ISSUE THREAD

**Issue by ssynical** [Roblox-Thot/DecalUploaderV2#1]
**Describe the bug**
 (this bug was fixed, look at bug below)
 
**Desktop:**
 - OS: Windows
 - Python Version: 3.10, 3.9, 3.11, 3.12

**Comment by ssynical** [comment]
this bug was fixed by just install rblx-open-cloud

but then this is also received on running OneUploader

Traceback (most recent call last):
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hello\Downloads\DecalUploaderV2-main\OneUploader.py", line 47, in <module>
    CREATOR = DecalClass(ROBLOSECURITY)
  File "C:\Users\hello\Downloads\DecalUploaderV2-main\DecalUploader\Uploader.py", line 13, in __init__
    self.__get_api_key__()
  File "C:\Users\hello\Downloads\DecalUploaderV2-main\DecalUploader\Uploader.py", line 27, in __get_api_key__
    response = requests.post("https://apis.roblox.com/cloud-authentication/v1/apiKey", json=payload, headers=headers, cookies={'.ROBLOSECURITY': self.cookie}).json()
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MilkKoun** [comment]
this means your account cookie has expired or the account has been Banned/Warned

**Comment by Roblox-Thot** [comment]
ya I still haven't added a error catching for stuff like bans, but ya that means the cookie was moderated or maybe invalid
